name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  NODE_VERSION: '20'

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository (main branch)
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Build
        run: |
          yarn install --immutable
          yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
